modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL=""

[[mods]]
modId="scarecrow"
version="1.0.0"
displayName="Scarecrow"
authors="CodDev"
description='''
A horror-themed Minecraft mod adding a GeckoLib-animated scarecrow entity with pose, dormant and hunting states.
'''

[[dependencies.scarecrow]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scarecrow]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scarecrow]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4,)"
    ordering="AFTER"
    side="BOTH"
